---

platform: linux

image_resource:
  type: docker-image
  source: {repository: lamlouis/create-slot}

inputs:
  - name: create-slot

run:
  path: create-slot/tasks/get-started-job/task.sh

params:
